### PR TITLE
Fix #1022: Gateway reboots with IntegerDivideByZero when trying to update firmware from server that does not return 'Content-length'

### LINKED ISSUE #1022: Gateway reboots with IntegerDivideByZero when trying to update firmware from server that does not return 'Content-length'
```
I (566687) transport_base: [fw_update_task] [<NULL>] Configure size of TLS I/O buffers: in_content_len=16384, out_content_len=4096
I (566700) esp-tls: [fw_update_task] esp_tls_init: tls=0x3ffe0b04
I (566758) esp-tls: [fw_update_task] Hostname 'my-https-server.local' resolved to 192.168.1.145
I (566809) esp-tls: [fw_update_task] esp_tls_tcp_connect: Open socket 54 for 192.168.1.145:8000
I (566814) http_download: [fw_update_task/1] HTTP_EVENT_ON_CONNECTED
I (566817) http_download: [fw_update_task/1] HTTP_EVENT_HEADER_SENT
I (566824) http_download: [fw_update_task/1] HTTP_EVENT_ON_HEADER, key=Content-type, value=application/octet-stream
I (566833) ADV_POST_TASK: [adv_post_task/5] Advs cnt: 7
I (566839) http_download: [fw_update_task/1] HTTP_EVENT_ON_HEADER, key=Cache-Control, value=no-store, no-cache, must-revalidate, max-age=0
I (566852) http_download: [fw_update_task/1] HTTP_EVENT_ON_HEADER, key=Pragma, value=no-cache
I (566861) fw_update: [fw_update_task/1] Write to OTA-partition ota_1, offset 0, size 1908
Guru Meditation Error: Core  0 panic'ed (IntegerDivideByZero). Exception was unhandled.

Core  0 register dump:
PC      : 0x400e093a  PS      : 0x00060630  A0      : 0x800ed36a  A1      : 0x3ffe9dd0  
A2      : 0x3ffe6f80  A3      : 0x00000774  A4      : 0x0000ba54  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x3ffea1ec  A8      : 0x00009510  A9      : 0x3ffe9d80  
A10     : 0x00000003  A11     : 0x000174a8  A12     : 0x3f408dcc  A13     : 0x8ed73ab6  
A14     : 0x3ffe9d80  A15     : 0x3ffe60a0  SAR     : 0x00000004  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffe  

Backtrace:0x400e0937:0x3ffe9dd0 0x400ed367:0x3ffe9e40 0x4017efd5:0x3ffe9e90 0x4017f30d:0x3ffe9ec0 0x40175f21:0x3ffe9ef0 0x4017f949:0x3ffe9f60 0x40180b9a:0x3ffe9f90 0x400eb97f:0x3ffe9fe0 0x400ed6b7:0x3ffea050 0x400edc69:0x3ffea0c0 0x400edd29:0x3ffea140 0x400eddb3:0x3ffea170 0x400e0340:0x3ffea1c0 0x400e070c:0x3ffea240 0x400e081d:0x3ffea290 0x400e143c:0x3ffea2e0 0x400e1718:0x3ffea330 0x401770bd:0x3ffea370 0x4008ad72:0x3ffea3a0


ELF file SHA256: 13a1e234fe494f6a

Rebooting...
E (566870) reset_info: __wrap_panic_restart: PANIC: Guru Meditation Error: Core  0 panic'ed (IntegerDivideByZero). Exception was unhandled.

Core  0 register dump:
PC      : 0x400e093a  PS      : 0x00060630  A0      : 0x800ed36a  A1      : 0x3ffe9dd0  
A2      : 0x3ffe6f80  A3      : 0x00000774  A4      : 0x0000ba54  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x3ffea1ec  A8      : 0x00009510  A9      : 0x3ffe9d80  
A10     : 0x00000003  A11     : 0x000174a8  A12     : 0x3f408dcc  A13     : 0x8ed73ab6  
A14     : 0x3ffe9d80  A15     : 0x3ffe60a0  SAR     : 0x00000004  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffe  

Backtrace:0x400e0937:0x3ffe9dd0 0x400ed367:0x3ffe9e40 0x4017efd5:0x3ffe9e90 0x4017f30d:0x3ffe9ec0 0x40175f21:0x3ffe9ef0 0x4017f949:0x3ffe9f60 0x40180b9a:0x3ffe9f90 0x400eb97f:0x3ffe9fe0 0x400ed6b7:0x3ffea050 0x400edc69:0x3ffea0c0 0x400edd29:0x3ffea140 0x400eddb3:0x3ffea170 0x400e0340:0x3ffea1c0 0x400e070c:0x3ffea240 0x400e081d:0x3ffea290 0x400e143c:0x3ffea2e0 0x400e1718:0x3ffea330 0x401770bd:0x3ffea370 0x4008ad72:0x3ffea3a0


ELF file SHA256: 13a1e234fe494f6a

Rebooting...
```

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

File: main/fw_update.c [hunk 1]
```diff
@@ -36,6 +36,9 @@
 
 #define FW_UPDATE_DELAY_BEFORE_REBOOT_SECONDS (5U)
 
+#define FW_UPDATE_MAX_OTA_PARTITION_SIZE  (4U * 1024U * 1024U)
```
Comment (ojousima) [inline main/fw_update.c:39]: Is there a way to retrieve these values off the partition table file? 

If partition table is ever changed, I'm surprised if we remember to adjust these constants

Comment (ojousima) [reply main/fw_update.c:39]: Actually, since these constants are used only for calculating percentages in UI in case file size is not reported, I think this is ok as long as nothing breaks on values > 100%

**Comment by TheSomeMan** [comment]
> Thanks, please see comment about percentage being > 100 % in some edge case.

I checked how UI handles the percentage > 100. In this case the progress bar is displayed 100% complete.
